### ISSUE TITLE
可以去我订阅转换仓库PR一下，我把规则合并到远程配置列表里去

### ISSUE THREAD

**Issue by youshandefeiyang** [cutethotw/ClashRule#10]
对长期更新的远程配置文件，可以直接放在通用栏里 https://github.com/youshandefeiyang/sub-web-modify
![FC71F48A-5F58-4926-AAC7-47F3BD9EFC10](https://user-images.githubusercontent.com/63959400/213315324-e7b7cfe9-076d-4f9c-863f-33f5818bef14.png)

**Comment by cutethotw** [comment]
刚已经PR了，之前这几天有点忙一直没看到不好意思哈，那边看下合适不，有需要改动的那边直接改都行哈

**Comment by youshandefeiyang** [comment]
好的，我已经改正添加了
