### ISSUE TITLE
知乎提示网络异常

### ISSUE THREAD

**Issue by p1ayer222** [cutethotw/ClashRule#13]
clash加载肥羊转换后的配置，访问知乎会提示网络异常，使用的是rule，fakeip模式
```
进入知乎
系统监测到您的网络环境存在异常，为保证您的正常访问，请点击下方验证按钮进行验证。在您验证完成前，该提示将多次出现
```
![image](https://github.com/cutethotw/ClashRule/assets/35835318/13f92d4d-91c3-41e1-b47d-024dc2b6079b)

**Comment by cutethotw** [comment]
有clash的分流相关信息么？Connections或Logs什么的以及策略组选择

**Comment by p1ayer222** [comment]
> 有clash的分流相关信息么？Connections或Logs什么的以及策略组选择

有一份openclash 的内核日志
[OpenClash-2023-8-3-14-24-1.log](https://github.com/cutethotw/ClashRule/files/12247541/OpenClash-2023-8-3-14-24-1.log)
