### ISSUE TITLE
chatgpt分流错误

### ISSUE THREAD

**Issue by Asakushen** [cutethotw/ClashRule#14]
目前发现会错误的将b站视频分流到chatgpt规则，
![image](https://github.com/cutethotw/ClashRule/assets/74193315/b411c435-9923-4675-9cfc-2a1d2cb3cf1e)
upos-hz-mirrorakam.akamaized.net
upos-hz-mirrorakam.akamaized.net:443
DomainSuffix (akamaized.net)
经查询此为b站使用的海外CDN
![image](https://github.com/cutethotw/ClashRule/assets/74193315/6358eafc-d7f3-4ece-a1c4-f014102d37f1)

**Comment by cutethotw** [comment]
检测了一下，是ChatGPT 分流里用到了这个CDN，已暂时注释掉，如果有影响再进行测试调整，感谢反馈
