### ISSUE TITLE
google play

### ISSUE THREAD

**Issue by hoowong** [cutethotw/ClashRule#17]
能不能增加一个google play不走香港

**Comment by cutethotw** [comment]
可以fork后自己改

**Comment by hoowong** [comment]
> 可以fork后自己改

主要是不会，基本上机场默认都有香港 很多香港被识别为国内导致无法通过googleplay下载更新 访问没有问题下载不行 如果新增一个手动选项 随便选个节点也可以解决 望采纳

**Comment by cutethotw** [comment]
无法使用google play是节点解锁问题，与地区无关，可以更换质量更好的节点
