### ISSUE TITLE
Steam规则

### ISSUE THREAD

**Issue by Rushbe2021** [cutethotw/ClashRule#19]
能不能增加一个steam规则，像魔界的那种
![image](https://github.com/cutethotw/ClashRule/assets/89636294/5ff13ff7-deb9-421f-81c2-885513de5767)
试了一下
自带的游戏平台规则选香港后steam还是直连

**Comment by cutethotw** [comment]
游戏平台已经包含steam，直连的截图贴下看看

**Comment by Rushbe2021** [comment]
已经解决了，原来是和steam++冲突了，谢谢！

**Comment by cutethotw** [comment]
ok解决了就行，有问题随时反馈
