### ISSUE TITLE
配置经常失效怎么回事？

### ISSUE THREAD

**Issue by billowssun** [cutethotw/ClashRule#20]
有时候更新后恢复原服务商的分流规则，有时下载规则不全。

**Comment by cutethotw** [comment]
可能是后端地址的原因，可以试下——https://sub.noak.me/

**Comment by billowssun** [comment]
> 可能是后端地址的原因，可以试下——https://sub.noak.me/

打不开呀

**Comment by cutethotw** [comment]
……用法不对，参考远程配置用法即可

**Comment by billowssun** [comment]
换了个后端没有出现问题了
