### ISSUE TITLE
向 巴哈姆特 规则集中加入香港节点

### ISSUE THREAD

**Issue by shibeta** [cutethotw/ClashRule#24]
24年6月开始，巴哈姆特和动画疯开始向香港提供服务，经测试香港节点可以访问巴哈姆特。
目前巴哈姆特规则集中仅自动包含了台湾节点而没有包含香港节点，因此希望能将香港节点自动添加到巴哈姆特规则集中。

**Comment by cutethotw** [comment]
好的，已添加
