### ISSUE TITLE
规则模式google授权浏览器拓展错误

### ISSUE THREAD

**Issue by sha7dowXX** [cutethotw/ClashRule#8]
规则模式google授权浏览器拓展错误，只有请求授权时直连，更换语言可解决，大概是哪个ip被直连了

**Comment by sha7dowXX** [comment]
www.gstatic.com
被直连

**Comment by cutethotw** [comment]
这里引用的是——https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list ——这个规则哈，DOMAIN-SUFFIX,www.gstatic.com

**Comment by sha7dowXX** [comment]
估计google随翻译一起撤了不少大陆节点

**Comment by sha7dowXX** [comment]
> 这里引用的是——https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list ——这个规则哈，DOMAIN-SUFFIX,www.gstatic.com

- DOMAIN-SUFFIX,gstatic.com,🚀 国外流量  #谷歌大陆节点代理
- DOMAIN-SUFFIX,googleapis.cn,🚀 国外流量  #谷歌play
- DOMAIN,api.nopecha.com,DIRECT   #浏览器自动验证码拓展nopecha解除ip封禁
- DOMAIN,www2.deepl.com,DIRECT  #DeepL直连翻译

补充的几条规则

**Comment by cutethotw** [comment]
好的，我补充一下哈，感谢感谢
